In [1]:
import numpy as np
import pandas as pd

In [2]:
X = np.genfromtxt("hw01_data_points.csv", delimiter = ",", dtype = str)
y = np.genfromtxt("hw01_class_labels.csv", delimiter = ",", dtype = int)

In [3]:
# STEP 3
# first 50000 data points should be included to train
# remaining 43925 data points should be included to test
# should return X_train, y_train, X_test, and y_test
def train_test_split(X, y):
    # your implementation starts below
    X_train=X[0:50000]
    y_train=y[0:50000]
    X_test=X[50000:93925]
    y_test=y[50000:93925]
    # your implementation ends above
    
    return(X_train, y_train, X_test, y_test)

X_train, y_train, X_test, y_test = train_test_split(X, y)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(50000, 7)
(50000,)
(43925, 7)
(43925,)


In [4]:
# STEP 4
# assuming that there are K classes
# should return a numpy array with shape (K,)
def estimate_prior_probabilities(y):
    # your implementation starts below
    class_priors = np.array([np.mean(y == (c + 1)) for c in range(2)])
    # your implementation ends above
    return(class_priors)

class_priors = estimate_prior_probabilities(y_train)
print(class_priors)



[0.0452 0.9548]


In [5]:
# STEP 5
# assuming that there are K classes and D features
# should return four numpy arrays with shape (K, D)
def estimate_nucleotide_probabilities(X, y):
    # your implementation starts below
    #calculating pAcd
    pAcd = np.array([[np.sum((y == c+1) & (X[:, d] == 'A')) for d in range(7)] for c in range(2)] )
    
    number_of_c_one= np.array([np.mean(y == (c + 1)) for c in range(2)])[0] * len(y)
    number_of_c_two= len(y)-number_of_c_one
    
    pAcd1=pAcd[0]/number_of_c_one 
    pAcd2=pAcd[1]/number_of_c_two 
    
    pAcd= np.array([pAcd1,pAcd2])
    
    
    #calculating pCcd
    pCcd = np.array([[np.sum((y == c+1) & (X[:, d] == 'C')) for d in range(7)] for c in range(2)] )
    
    
    
    pCcd1=pCcd[0]/number_of_c_one 
    pCcd2=pCcd[1]/number_of_c_two 
    
    pCcd= np.array([pCcd1,pCcd2])
    
    
    #calculating pGcd
    
    pGcd = np.array([[np.sum((y == c+1) & (X[:, d] == 'G')) for d in range(7)] for c in range(2)] )
    

    
    pGcd1=pGcd[0]/number_of_c_one 
    pGcd2=pGcd[1]/number_of_c_two 
    
    pGcd= np.array([pGcd1,pGcd2])
    
    
    
    #pTcd
    
    pTcd = np.array([[np.sum((y == c+1) & (X[:, d] == 'T')) for d in range(7)] for c in range(2)] )
    
    
    
    pTcd1=pTcd[0]/number_of_c_one 
    pTcd2=pTcd[1]/number_of_c_two 
    
    pTcd= np.array([pTcd1,pTcd2])
    
    return(pAcd,pCcd,pGcd,pTcd)

pAcd,pCcd,pGcd,pTcd= estimate_nucleotide_probabilities(X_train, y_train)

print(pAcd)
print(pCcd)
print(pGcd)
print(pTcd)


[[0.32345133 0.64424779 0.09424779 0.56681416 0.68938053 0.0800885
  0.16371681]
 [0.25450356 0.2728739  0.30117302 0.19522413 0.25473398 0.23990364
  0.26292417]]
[[0.37433628 0.12123894 0.02964602 0.03230088 0.08053097 0.05221239
  0.16725664]
 [0.21979472 0.2340176  0.06514453 0.20605362 0.21214914 0.24767491
  0.21723921]]
[[0.18716814 0.1199115  0.81814159 0.37477876 0.11371681 0.79513274
  0.19690265]
 [0.24805195 0.24434437 0.2676791  0.33636364 0.22869711 0.23104315
  0.23016339]]
[[0.11504425 0.11460177 0.0579646  0.02610619 0.11637168 0.07256637
  0.47212389]
 [0.27764977 0.24876414 0.36600335 0.26235861 0.30441977 0.2813783
  0.28967323]]


In [6]:
# STEP 6
# assuming that there are N data points and K classes
# should return a numpy array with shape (N, K)
def calculate_score_values(X, pAcd, pCcd, pGcd, pTcd, class_priors):
    # your implementation starts below
   
    
    
    
    sumA= np.sum ((np.array([[np.sum((X[c, d] == 'A')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pAcd[0]), axis=1,keepdims=True)
    sumG= np.sum ((np.array([[np.sum((X[c, d] == 'G')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pGcd[0]), axis=1,keepdims=True)
    sumT= np.sum ((np.array([[np.sum((X[c, d] == 'T')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pTcd[0]), axis=1,keepdims=True)
    sumC= np.sum ((np.array([[np.sum((X[c, d] == 'C')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pCcd[0]), axis=1,keepdims=True)
    log_prob=np.log(class_priors[0])
    summ=sumA+sumG+sumT+sumC+log_prob
    
    
    sumA2= np.sum ((np.array([[np.sum((X[c, d] == 'A')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pAcd[1]), axis=1,keepdims=True)
    sumG2= np.sum ((np.array([[np.sum((X[c, d] == 'G')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pGcd[1]), axis=1,keepdims=True)
    sumT2= np.sum ((np.array([[np.sum((X[c, d] == 'T')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pTcd[1]), axis=1,keepdims=True)
    sumC2= np.sum ((np.array([[np.sum((X[c, d] == 'C')) for d in range(7)] for c in range(len(X[:,1])) ]   )) * np.log(pCcd[1]), axis=1,keepdims=True)
    log_prob2=np.log(class_priors[1])
    summ2=sumA2+sumG2+sumT2+sumC2+log_prob2
    
    
   
   
  
    
    score_values=np.column_stack((summ,summ2))
    
    
    
    
    
    
    
    
    # your implementation ends above
    return(score_values)

scores_train = calculate_score_values(X_train, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_train)

scores_test = calculate_score_values(X_test, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_test)


[[-15.84302871  -9.3433522 ]
 [-16.73815388  -8.90270491]
 [-17.12201508  -8.87059123]
 ...
 [-12.64747986  -9.3077559 ]
 [-18.14584244  -9.54820083]
 [-14.67706629  -9.45002167]]
[[-17.02244643  -9.95385128]
 [-13.10176993  -9.42908242]
 [-12.61507938  -9.54180473]
 ...
 [-12.86990369  -9.21875465]
 [-12.90250138  -9.38540918]
 [-16.43266951  -9.37467256]]


In [7]:
# STEP 7
# assuming that there are K classes
# should return a numpy array with shape (K, K)
def calculate_confusion_matrix(y_truth, scores):
    # your implementation starts below
    
    
    
    y_pred = np.argmax(scores, axis=1) +1
    
    TN= np.sum((y_truth==1) & (y_pred==1))
    FN= np.sum((y_truth==2) & (y_pred==1))
    
    FP= np.sum((y_truth==1) & (y_pred==2))
    TP= np.sum((y_truth==2) & (y_pred==2))
    
    confusion_matrix = np.zeros((2, 2),dtype=int)
    
    confusion_matrix[0][0]=TN
    confusion_matrix[0][1]=FN
    confusion_matrix[1][0]=FP
    confusion_matrix[1][1]=TP


    return(confusion_matrix)

confusion_train = calculate_confusion_matrix(y_train, scores_train)
print(confusion_train)

confusion_test = calculate_confusion_matrix(y_test, scores_test)
print(confusion_test)

[[ 1066   484]
 [ 1194 47256]]
[[  891   416]
 [ 1057 41561]]
